version: "3.1"

services:
  postgres:
    image: postgres:16.4
    container_name: stocks-batch-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stocks_batch}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
    volumes:
      - stocks-batch-db-volume:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  stocks-batch-db-volume: