CREATE TABLE stocks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(25),              -- stock name (e.g., "AAPL")
    date       DATE            NOT NULL, -- Date of the stock record
    open       DECIMAL(19, 15) NOT NULL, -- Opening stock price with high precision
    high       DECIMAL(19, 15) NOT NULL, -- Highest stock price during the day
    low        DECIMAL(19, 15) NOT NULL, -- Lowest stock price during the day
    close      DECIMAL(19, 15) NOT NULL,-- Closing stock price
    adj_close  DECIMAL(19, 15) NOT NULL,-- Adjusted closing stock price
    volume     BIGINT          NOT NULL  -- Volume of stocks traded
);

CREATE UNIQUE INDEX idx_u_stocks_name_date ON stocks (name, date);

